# Generated by Django 5.2.8 on 2025-11-18 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('excludedFromAI', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='JobCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('customerName', models.CharField(max_length=100)),
                ('businessUnit', models.CharField(max_length=100)),
                ('budgetTime', models.IntegerField()),
                ('budgetCost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Specialism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForecastEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecastID', models.CharField(max_length=20, unique=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comwrap.employee')),
                ('jobCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comwrap.jobcode')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='specialisms',
            field=models.ManyToManyField(related_name='employees', to='comwrap.specialism'),
        ),
    ]
