# Generated by Django 5.2.7 on 2026-02-18 16:20

import comwrap.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
                ("excludedFromAI", models.BooleanField()),
                ("slug", models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ReplyEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ResourceBusinessUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Specialism",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="JobCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField()),
                ("customerName", models.CharField(max_length=100)),
                ("businessUnit", models.CharField(max_length=100)),
                (
                    "jobOrigin",
                    models.CharField(
                        choices=[
                            ("A", "A - Order or eq."),
                            ("B", "B - Formal Effort"),
                            ("C", "C - Other effort"),
                            ("D", "D - Forecast COGE"),
                        ],
                        default="A",
                        max_length=1,
                    ),
                ),
                ("budgetTime", models.IntegerField()),
                ("budgetCost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("startDate", models.DateField()),
                ("endDate", models.DateField()),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("O", "O - Open"),
                            ("B", "B - Blocked"),
                            ("C", "C - Closed"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "employees",
                    models.ManyToManyField(
                        related_name="jobCodes", to="comwrap.employee"
                    ),
                ),
                (
                    "replyEntity",
                    models.ForeignKey(
                        default=comwrap.models.get_default_reply_entity,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comwrap.replyentity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Forecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("forecastID", models.CharField(max_length=20, unique=True)),
                ("date", models.DateField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "jobCode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comwrap.jobcode",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="employee",
            name="resourceBU",
            field=models.ForeignKey(
                default=comwrap.models.get_default_resource_bu,
                on_delete=django.db.models.deletion.CASCADE,
                to="comwrap.resourcebusinessunit",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="specialisms",
            field=models.ManyToManyField(
                related_name="employees", to="comwrap.specialism"
            ),
        ),
        migrations.CreateModel(
            name="ForecastAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("daysAllocated", models.DecimalField(decimal_places=1, max_digits=5)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="comwrap.employee",
                    ),
                ),
                (
                    "forecast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="comwrap.forecast",
                    ),
                ),
            ],
            options={
                "unique_together": {("forecast", "employee")},
            },
        ),
    ]
