# Generated by Django 5.2.8 on 2025-11-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comwrap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastentry',
            name='hoursAllocated',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
