# Generated by Django 5.2.8 on 2025-11-19 13:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comwrap', '0002_forecastentry_hoursallocated'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastentry',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
