# Generated by Django 5.2.7 on 2026-02-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comwrap', '0004_employee_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcode',
            name='employees',
            field=models.ManyToManyField(related_name='jobCodes', to='comwrap.employee'),
        ),
    ]
