# Generated by Django 5.2.7 on 2026-02-11 16:14

import comwrap.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comwrap", "0004_employee_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReplyEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ResourceBusinessUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="employee",
            name="jobCodes",
            field=models.ManyToManyField(
                blank=True, related_name="employees", to="comwrap.jobcode"
            ),
        ),
        migrations.AddField(
            model_name="jobcode",
            name="jobOrigin",
            field=models.CharField(
                choices=[
                    ("A", "A - Order or eq."),
                    ("B", "B - Formal Effort"),
                    ("C", "C - Other effort"),
                    ("D", "D - Forecast COGE"),
                ],
                default="A",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="jobcode",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("O", "O - Open"), ("B", "B - Blocked"), ("C", "C - Closed")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="jobcode",
            name="replyEntity",
            field=models.ForeignKey(
                default=comwrap.models.get_default_reply_entity,
                on_delete=django.db.models.deletion.CASCADE,
                to="comwrap.replyentity",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="resourceBU",
            field=models.ForeignKey(
                default=comwrap.models.get_default_resource_bu,
                on_delete=django.db.models.deletion.CASCADE,
                to="comwrap.resourcebusinessunit",
            ),
        ),
    ]
