# Generated by Django 5.2.7 on 2026-02-11 18:05

import comwrap.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comwrap', '0005_jobcode_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceBusinessUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobcode',
            name='employees',
        ),
        migrations.AddField(
            model_name='jobcode',
            name='jobOrigin',
            field=models.CharField(choices=[('A', 'A - Order or eq.'), ('B', 'B - Formal Effort'), ('C', 'C - Other effort'), ('D', 'D - Forecast COGE')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='jobcode',
            name='status',
            field=models.CharField(blank=True, choices=[('O', 'O - Open'), ('B', 'B - Blocked'), ('C', 'C - Closed')], max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecastID', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField()),
                ('jobCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comwrap.jobcode')),
            ],
        ),
        migrations.CreateModel(
            name='ForecastAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoursAllocated', models.DecimalField(decimal_places=1, max_digits=5)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='comwrap.employee')),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='comwrap.forecast')),
            ],
            options={
                'unique_together': {('forecast', 'employee')},
            },
        ),
        migrations.AddField(
            model_name='jobcode',
            name='replyEntity',
            field=models.ForeignKey(default=comwrap.models.get_default_reply_entity, on_delete=django.db.models.deletion.CASCADE, to='comwrap.replyentity'),
        ),
        migrations.AddField(
            model_name='employee',
            name='resourceBU',
            field=models.ForeignKey(default=comwrap.models.get_default_resource_bu, on_delete=django.db.models.deletion.CASCADE, to='comwrap.resourcebusinessunit'),
        ),
        migrations.DeleteModel(
            name='ForecastEntry',
        ),
    ]
