# Generated by Django 5.2.7 on 2026-02-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comwrap', '0006_replyentity_resourcebusinessunit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcode',
            name='employees',
            field=models.ManyToManyField(related_name='jobCodes', to='comwrap.employee'),
        ),
    ]
