# Generated by Django 5.2.7 on 2026-02-11 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comwrap', '0007_jobcode_employees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forecastallocation',
            old_name='hoursAllocated',
            new_name='daysAllocated',
        ),
    ]
