# Generated by Django 5.2.7 on 2026-02-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comwrap', '0008_rename_hoursallocated_forecastallocation_daysallocated'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
